version: '3'
services:
  database:
    container_name: search-app-db
    image: "postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=devdatabase
      - POSTGRES_USER=development
      - POSTGRES_DB=search-app
    volumes:
      - ./database/data:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: ./api/dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - "database"
    restart: unless-stopped
    environment:
      - NODE_ENV=prod
      - DB_HOST=database