FROM mhart/alpine-node:12

WORKDIR /site

COPY ./site .

RUN npm i

RUN npm uninstall node-sass && npm install node-sass

RUN npm run build

WORKDIR /api

RUN mv /site/build ./build

COPY package.json ./

COPY ./api .

RUN npm i

CMD ["npm", "start"]
